-- !! DO NOT EDIT
{-|
(Automatically generated by @src\/Util\/GenerateHtmlTCombinators.hs:49@)

This module wraps all exports of "Text.Blaze.Html4.FrameSet" using 'wrapMarkup' and 'wrapMarkup'.
-}
module Text.BlazeT.Html4.FrameSet
   (module Text.BlazeT.Html4.FrameSet
   ,module Text.BlazeT.Html
   ) where
import qualified Text.Blaze.Html4.FrameSet
import           Text.BlazeT
import           Text.BlazeT.Html
import           Text.BlazeT.Internal

docTypeHtml :: Markup2
docTypeHtml = wrapMarkup2 Text.Blaze.Html4.FrameSet.docTypeHtml
a :: Markup2
a = wrapMarkup2 Text.Blaze.Html4.FrameSet.a
abbr :: Markup2
abbr = wrapMarkup2 Text.Blaze.Html4.FrameSet.abbr
acronym :: Markup2
acronym = wrapMarkup2 Text.Blaze.Html4.FrameSet.acronym
address :: Markup2
address = wrapMarkup2 Text.Blaze.Html4.FrameSet.address
b :: Markup2
b = wrapMarkup2 Text.Blaze.Html4.FrameSet.b
bdo :: Markup2
bdo = wrapMarkup2 Text.Blaze.Html4.FrameSet.bdo
big :: Markup2
big = wrapMarkup2 Text.Blaze.Html4.FrameSet.big
blockquote :: Markup2
blockquote = wrapMarkup2 Text.Blaze.Html4.FrameSet.blockquote
body :: Markup2
body = wrapMarkup2 Text.Blaze.Html4.FrameSet.body
button :: Markup2
button = wrapMarkup2 Text.Blaze.Html4.FrameSet.button
caption :: Markup2
caption = wrapMarkup2 Text.Blaze.Html4.FrameSet.caption
cite :: Markup2
cite = wrapMarkup2 Text.Blaze.Html4.FrameSet.cite
code :: Markup2
code = wrapMarkup2 Text.Blaze.Html4.FrameSet.code
colgroup :: Markup2
colgroup = wrapMarkup2 Text.Blaze.Html4.FrameSet.colgroup
dd :: Markup2
dd = wrapMarkup2 Text.Blaze.Html4.FrameSet.dd
del :: Markup2
del = wrapMarkup2 Text.Blaze.Html4.FrameSet.del
dfn :: Markup2
dfn = wrapMarkup2 Text.Blaze.Html4.FrameSet.dfn
div :: Markup2
div = wrapMarkup2 Text.Blaze.Html4.FrameSet.div
dl :: Markup2
dl = wrapMarkup2 Text.Blaze.Html4.FrameSet.dl
dt :: Markup2
dt = wrapMarkup2 Text.Blaze.Html4.FrameSet.dt
em :: Markup2
em = wrapMarkup2 Text.Blaze.Html4.FrameSet.em
fieldset :: Markup2
fieldset = wrapMarkup2 Text.Blaze.Html4.FrameSet.fieldset
form :: Markup2
form = wrapMarkup2 Text.Blaze.Html4.FrameSet.form
h1 :: Markup2
h1 = wrapMarkup2 Text.Blaze.Html4.FrameSet.h1
h2 :: Markup2
h2 = wrapMarkup2 Text.Blaze.Html4.FrameSet.h2
h3 :: Markup2
h3 = wrapMarkup2 Text.Blaze.Html4.FrameSet.h3
h4 :: Markup2
h4 = wrapMarkup2 Text.Blaze.Html4.FrameSet.h4
h5 :: Markup2
h5 = wrapMarkup2 Text.Blaze.Html4.FrameSet.h5
h6 :: Markup2
h6 = wrapMarkup2 Text.Blaze.Html4.FrameSet.h6
head :: Markup2
head = wrapMarkup2 Text.Blaze.Html4.FrameSet.head
html :: Markup2
html = wrapMarkup2 Text.Blaze.Html4.FrameSet.html
i :: Markup2
i = wrapMarkup2 Text.Blaze.Html4.FrameSet.i
ins :: Markup2
ins = wrapMarkup2 Text.Blaze.Html4.FrameSet.ins
kbd :: Markup2
kbd = wrapMarkup2 Text.Blaze.Html4.FrameSet.kbd
label :: Markup2
label = wrapMarkup2 Text.Blaze.Html4.FrameSet.label
legend :: Markup2
legend = wrapMarkup2 Text.Blaze.Html4.FrameSet.legend
li :: Markup2
li = wrapMarkup2 Text.Blaze.Html4.FrameSet.li
map :: Markup2
map = wrapMarkup2 Text.Blaze.Html4.FrameSet.map
noscript :: Markup2
noscript = wrapMarkup2 Text.Blaze.Html4.FrameSet.noscript
object :: Markup2
object = wrapMarkup2 Text.Blaze.Html4.FrameSet.object
ol :: Markup2
ol = wrapMarkup2 Text.Blaze.Html4.FrameSet.ol
optgroup :: Markup2
optgroup = wrapMarkup2 Text.Blaze.Html4.FrameSet.optgroup
option :: Markup2
option = wrapMarkup2 Text.Blaze.Html4.FrameSet.option
p :: Markup2
p = wrapMarkup2 Text.Blaze.Html4.FrameSet.p
pre :: Markup2
pre = wrapMarkup2 Text.Blaze.Html4.FrameSet.pre
q :: Markup2
q = wrapMarkup2 Text.Blaze.Html4.FrameSet.q
samp :: Markup2
samp = wrapMarkup2 Text.Blaze.Html4.FrameSet.samp
script :: Markup2
script = wrapMarkup2 Text.Blaze.Html4.FrameSet.script
select :: Markup2
select = wrapMarkup2 Text.Blaze.Html4.FrameSet.select
small :: Markup2
small = wrapMarkup2 Text.Blaze.Html4.FrameSet.small
span :: Markup2
span = wrapMarkup2 Text.Blaze.Html4.FrameSet.span
strong :: Markup2
strong = wrapMarkup2 Text.Blaze.Html4.FrameSet.strong
style :: Markup2
style = wrapMarkup2 Text.Blaze.Html4.FrameSet.style
sub :: Markup2
sub = wrapMarkup2 Text.Blaze.Html4.FrameSet.sub
sup :: Markup2
sup = wrapMarkup2 Text.Blaze.Html4.FrameSet.sup
table :: Markup2
table = wrapMarkup2 Text.Blaze.Html4.FrameSet.table
tbody :: Markup2
tbody = wrapMarkup2 Text.Blaze.Html4.FrameSet.tbody
td :: Markup2
td = wrapMarkup2 Text.Blaze.Html4.FrameSet.td
textarea :: Markup2
textarea = wrapMarkup2 Text.Blaze.Html4.FrameSet.textarea
tfoot :: Markup2
tfoot = wrapMarkup2 Text.Blaze.Html4.FrameSet.tfoot
th :: Markup2
th = wrapMarkup2 Text.Blaze.Html4.FrameSet.th
thead :: Markup2
thead = wrapMarkup2 Text.Blaze.Html4.FrameSet.thead
title :: Markup2
title = wrapMarkup2 Text.Blaze.Html4.FrameSet.title
tr :: Markup2
tr = wrapMarkup2 Text.Blaze.Html4.FrameSet.tr
tt :: Markup2
tt = wrapMarkup2 Text.Blaze.Html4.FrameSet.tt
ul :: Markup2
ul = wrapMarkup2 Text.Blaze.Html4.FrameSet.ul
var :: Markup2
var = wrapMarkup2 Text.Blaze.Html4.FrameSet.var
applet :: Markup2
applet = wrapMarkup2 Text.Blaze.Html4.FrameSet.applet
center :: Markup2
center = wrapMarkup2 Text.Blaze.Html4.FrameSet.center
dir :: Markup2
dir = wrapMarkup2 Text.Blaze.Html4.FrameSet.dir
font :: Markup2
font = wrapMarkup2 Text.Blaze.Html4.FrameSet.font
iframe :: Markup2
iframe = wrapMarkup2 Text.Blaze.Html4.FrameSet.iframe
isindex :: Markup2
isindex = wrapMarkup2 Text.Blaze.Html4.FrameSet.isindex
menu :: Markup2
menu = wrapMarkup2 Text.Blaze.Html4.FrameSet.menu
noframes :: Markup2
noframes = wrapMarkup2 Text.Blaze.Html4.FrameSet.noframes
s :: Markup2
s = wrapMarkup2 Text.Blaze.Html4.FrameSet.s
u :: Markup2
u = wrapMarkup2 Text.Blaze.Html4.FrameSet.u
frameset :: Markup2
frameset = wrapMarkup2 Text.Blaze.Html4.FrameSet.frameset
docType :: Markup
docType = wrapMarkup Text.Blaze.Html4.FrameSet.docType
area :: Markup
area = wrapMarkup Text.Blaze.Html4.FrameSet.area
br :: Markup
br = wrapMarkup Text.Blaze.Html4.FrameSet.br
col :: Markup
col = wrapMarkup Text.Blaze.Html4.FrameSet.col
hr :: Markup
hr = wrapMarkup Text.Blaze.Html4.FrameSet.hr
link :: Markup
link = wrapMarkup Text.Blaze.Html4.FrameSet.link
img :: Markup
img = wrapMarkup Text.Blaze.Html4.FrameSet.img
input :: Markup
input = wrapMarkup Text.Blaze.Html4.FrameSet.input
meta :: Markup
meta = wrapMarkup Text.Blaze.Html4.FrameSet.meta
param :: Markup
param = wrapMarkup Text.Blaze.Html4.FrameSet.param
basefont :: Markup
basefont = wrapMarkup Text.Blaze.Html4.FrameSet.basefont
frame :: Markup
frame = wrapMarkup Text.Blaze.Html4.FrameSet.frame

