-- !! DO NOT EDIT
{-|
(Automatically generated by @src\/Util\/GenerateHtmlTCombinators.hs:49@)

This module wraps all exports of "Text.Blaze.Html4.Strict" using 'wrapMarkup' and 'wrapMarkup'.
-}
module Text.BlazeT.Html4.Strict
   (module Text.BlazeT.Html4.Strict
   ,module Text.BlazeT.Html
   ) where
import qualified Text.Blaze.Html4.Strict
import           Text.BlazeT
import           Text.BlazeT.Html
import           Text.BlazeT.Internal

docTypeHtml :: Markup2
docTypeHtml = wrapMarkup2 Text.Blaze.Html4.Strict.docTypeHtml
a :: Markup2
a = wrapMarkup2 Text.Blaze.Html4.Strict.a
abbr :: Markup2
abbr = wrapMarkup2 Text.Blaze.Html4.Strict.abbr
acronym :: Markup2
acronym = wrapMarkup2 Text.Blaze.Html4.Strict.acronym
address :: Markup2
address = wrapMarkup2 Text.Blaze.Html4.Strict.address
b :: Markup2
b = wrapMarkup2 Text.Blaze.Html4.Strict.b
bdo :: Markup2
bdo = wrapMarkup2 Text.Blaze.Html4.Strict.bdo
big :: Markup2
big = wrapMarkup2 Text.Blaze.Html4.Strict.big
blockquote :: Markup2
blockquote = wrapMarkup2 Text.Blaze.Html4.Strict.blockquote
body :: Markup2
body = wrapMarkup2 Text.Blaze.Html4.Strict.body
button :: Markup2
button = wrapMarkup2 Text.Blaze.Html4.Strict.button
caption :: Markup2
caption = wrapMarkup2 Text.Blaze.Html4.Strict.caption
cite :: Markup2
cite = wrapMarkup2 Text.Blaze.Html4.Strict.cite
code :: Markup2
code = wrapMarkup2 Text.Blaze.Html4.Strict.code
colgroup :: Markup2
colgroup = wrapMarkup2 Text.Blaze.Html4.Strict.colgroup
dd :: Markup2
dd = wrapMarkup2 Text.Blaze.Html4.Strict.dd
del :: Markup2
del = wrapMarkup2 Text.Blaze.Html4.Strict.del
dfn :: Markup2
dfn = wrapMarkup2 Text.Blaze.Html4.Strict.dfn
div :: Markup2
div = wrapMarkup2 Text.Blaze.Html4.Strict.div
dl :: Markup2
dl = wrapMarkup2 Text.Blaze.Html4.Strict.dl
dt :: Markup2
dt = wrapMarkup2 Text.Blaze.Html4.Strict.dt
em :: Markup2
em = wrapMarkup2 Text.Blaze.Html4.Strict.em
fieldset :: Markup2
fieldset = wrapMarkup2 Text.Blaze.Html4.Strict.fieldset
form :: Markup2
form = wrapMarkup2 Text.Blaze.Html4.Strict.form
h1 :: Markup2
h1 = wrapMarkup2 Text.Blaze.Html4.Strict.h1
h2 :: Markup2
h2 = wrapMarkup2 Text.Blaze.Html4.Strict.h2
h3 :: Markup2
h3 = wrapMarkup2 Text.Blaze.Html4.Strict.h3
h4 :: Markup2
h4 = wrapMarkup2 Text.Blaze.Html4.Strict.h4
h5 :: Markup2
h5 = wrapMarkup2 Text.Blaze.Html4.Strict.h5
h6 :: Markup2
h6 = wrapMarkup2 Text.Blaze.Html4.Strict.h6
head :: Markup2
head = wrapMarkup2 Text.Blaze.Html4.Strict.head
html :: Markup2
html = wrapMarkup2 Text.Blaze.Html4.Strict.html
i :: Markup2
i = wrapMarkup2 Text.Blaze.Html4.Strict.i
ins :: Markup2
ins = wrapMarkup2 Text.Blaze.Html4.Strict.ins
kbd :: Markup2
kbd = wrapMarkup2 Text.Blaze.Html4.Strict.kbd
label :: Markup2
label = wrapMarkup2 Text.Blaze.Html4.Strict.label
legend :: Markup2
legend = wrapMarkup2 Text.Blaze.Html4.Strict.legend
li :: Markup2
li = wrapMarkup2 Text.Blaze.Html4.Strict.li
map :: Markup2
map = wrapMarkup2 Text.Blaze.Html4.Strict.map
noscript :: Markup2
noscript = wrapMarkup2 Text.Blaze.Html4.Strict.noscript
object :: Markup2
object = wrapMarkup2 Text.Blaze.Html4.Strict.object
ol :: Markup2
ol = wrapMarkup2 Text.Blaze.Html4.Strict.ol
optgroup :: Markup2
optgroup = wrapMarkup2 Text.Blaze.Html4.Strict.optgroup
option :: Markup2
option = wrapMarkup2 Text.Blaze.Html4.Strict.option
p :: Markup2
p = wrapMarkup2 Text.Blaze.Html4.Strict.p
pre :: Markup2
pre = wrapMarkup2 Text.Blaze.Html4.Strict.pre
q :: Markup2
q = wrapMarkup2 Text.Blaze.Html4.Strict.q
samp :: Markup2
samp = wrapMarkup2 Text.Blaze.Html4.Strict.samp
script :: Markup2
script = wrapMarkup2 Text.Blaze.Html4.Strict.script
select :: Markup2
select = wrapMarkup2 Text.Blaze.Html4.Strict.select
small :: Markup2
small = wrapMarkup2 Text.Blaze.Html4.Strict.small
span :: Markup2
span = wrapMarkup2 Text.Blaze.Html4.Strict.span
strong :: Markup2
strong = wrapMarkup2 Text.Blaze.Html4.Strict.strong
style :: Markup2
style = wrapMarkup2 Text.Blaze.Html4.Strict.style
sub :: Markup2
sub = wrapMarkup2 Text.Blaze.Html4.Strict.sub
sup :: Markup2
sup = wrapMarkup2 Text.Blaze.Html4.Strict.sup
table :: Markup2
table = wrapMarkup2 Text.Blaze.Html4.Strict.table
tbody :: Markup2
tbody = wrapMarkup2 Text.Blaze.Html4.Strict.tbody
td :: Markup2
td = wrapMarkup2 Text.Blaze.Html4.Strict.td
textarea :: Markup2
textarea = wrapMarkup2 Text.Blaze.Html4.Strict.textarea
tfoot :: Markup2
tfoot = wrapMarkup2 Text.Blaze.Html4.Strict.tfoot
th :: Markup2
th = wrapMarkup2 Text.Blaze.Html4.Strict.th
thead :: Markup2
thead = wrapMarkup2 Text.Blaze.Html4.Strict.thead
title :: Markup2
title = wrapMarkup2 Text.Blaze.Html4.Strict.title
tr :: Markup2
tr = wrapMarkup2 Text.Blaze.Html4.Strict.tr
tt :: Markup2
tt = wrapMarkup2 Text.Blaze.Html4.Strict.tt
ul :: Markup2
ul = wrapMarkup2 Text.Blaze.Html4.Strict.ul
var :: Markup2
var = wrapMarkup2 Text.Blaze.Html4.Strict.var
docType :: Markup
docType = wrapMarkup Text.Blaze.Html4.Strict.docType
area :: Markup
area = wrapMarkup Text.Blaze.Html4.Strict.area
br :: Markup
br = wrapMarkup Text.Blaze.Html4.Strict.br
col :: Markup
col = wrapMarkup Text.Blaze.Html4.Strict.col
hr :: Markup
hr = wrapMarkup Text.Blaze.Html4.Strict.hr
link :: Markup
link = wrapMarkup Text.Blaze.Html4.Strict.link
img :: Markup
img = wrapMarkup Text.Blaze.Html4.Strict.img
input :: Markup
input = wrapMarkup Text.Blaze.Html4.Strict.input
meta :: Markup
meta = wrapMarkup Text.Blaze.Html4.Strict.meta
param :: Markup
param = wrapMarkup Text.Blaze.Html4.Strict.param

