-- !! DO NOT EDIT
{-|
(Automatically generated by @src\/Util\/GenerateHtmlTCombinators.hs:49@)

This module wraps all exports of "Text.Blaze.Html4.Transitional" using 'wrapMarkup' and 'wrapMarkup'.
-}
module Text.BlazeT.Html4.Transitional
   (module Text.BlazeT.Html4.Transitional
   ,module Text.BlazeT.Html
   ) where
import qualified Text.Blaze.Html4.Transitional
import           Text.BlazeT
import           Text.BlazeT.Html
import           Text.BlazeT.Internal

docTypeHtml :: Markup2
docTypeHtml = wrapMarkup2 Text.Blaze.Html4.Transitional.docTypeHtml
a :: Markup2
a = wrapMarkup2 Text.Blaze.Html4.Transitional.a
abbr :: Markup2
abbr = wrapMarkup2 Text.Blaze.Html4.Transitional.abbr
acronym :: Markup2
acronym = wrapMarkup2 Text.Blaze.Html4.Transitional.acronym
address :: Markup2
address = wrapMarkup2 Text.Blaze.Html4.Transitional.address
b :: Markup2
b = wrapMarkup2 Text.Blaze.Html4.Transitional.b
bdo :: Markup2
bdo = wrapMarkup2 Text.Blaze.Html4.Transitional.bdo
big :: Markup2
big = wrapMarkup2 Text.Blaze.Html4.Transitional.big
blockquote :: Markup2
blockquote = wrapMarkup2 Text.Blaze.Html4.Transitional.blockquote
body :: Markup2
body = wrapMarkup2 Text.Blaze.Html4.Transitional.body
button :: Markup2
button = wrapMarkup2 Text.Blaze.Html4.Transitional.button
caption :: Markup2
caption = wrapMarkup2 Text.Blaze.Html4.Transitional.caption
cite :: Markup2
cite = wrapMarkup2 Text.Blaze.Html4.Transitional.cite
code :: Markup2
code = wrapMarkup2 Text.Blaze.Html4.Transitional.code
colgroup :: Markup2
colgroup = wrapMarkup2 Text.Blaze.Html4.Transitional.colgroup
dd :: Markup2
dd = wrapMarkup2 Text.Blaze.Html4.Transitional.dd
del :: Markup2
del = wrapMarkup2 Text.Blaze.Html4.Transitional.del
dfn :: Markup2
dfn = wrapMarkup2 Text.Blaze.Html4.Transitional.dfn
div :: Markup2
div = wrapMarkup2 Text.Blaze.Html4.Transitional.div
dl :: Markup2
dl = wrapMarkup2 Text.Blaze.Html4.Transitional.dl
dt :: Markup2
dt = wrapMarkup2 Text.Blaze.Html4.Transitional.dt
em :: Markup2
em = wrapMarkup2 Text.Blaze.Html4.Transitional.em
fieldset :: Markup2
fieldset = wrapMarkup2 Text.Blaze.Html4.Transitional.fieldset
form :: Markup2
form = wrapMarkup2 Text.Blaze.Html4.Transitional.form
h1 :: Markup2
h1 = wrapMarkup2 Text.Blaze.Html4.Transitional.h1
h2 :: Markup2
h2 = wrapMarkup2 Text.Blaze.Html4.Transitional.h2
h3 :: Markup2
h3 = wrapMarkup2 Text.Blaze.Html4.Transitional.h3
h4 :: Markup2
h4 = wrapMarkup2 Text.Blaze.Html4.Transitional.h4
h5 :: Markup2
h5 = wrapMarkup2 Text.Blaze.Html4.Transitional.h5
h6 :: Markup2
h6 = wrapMarkup2 Text.Blaze.Html4.Transitional.h6
head :: Markup2
head = wrapMarkup2 Text.Blaze.Html4.Transitional.head
html :: Markup2
html = wrapMarkup2 Text.Blaze.Html4.Transitional.html
i :: Markup2
i = wrapMarkup2 Text.Blaze.Html4.Transitional.i
ins :: Markup2
ins = wrapMarkup2 Text.Blaze.Html4.Transitional.ins
kbd :: Markup2
kbd = wrapMarkup2 Text.Blaze.Html4.Transitional.kbd
label :: Markup2
label = wrapMarkup2 Text.Blaze.Html4.Transitional.label
legend :: Markup2
legend = wrapMarkup2 Text.Blaze.Html4.Transitional.legend
li :: Markup2
li = wrapMarkup2 Text.Blaze.Html4.Transitional.li
map :: Markup2
map = wrapMarkup2 Text.Blaze.Html4.Transitional.map
noscript :: Markup2
noscript = wrapMarkup2 Text.Blaze.Html4.Transitional.noscript
object :: Markup2
object = wrapMarkup2 Text.Blaze.Html4.Transitional.object
ol :: Markup2
ol = wrapMarkup2 Text.Blaze.Html4.Transitional.ol
optgroup :: Markup2
optgroup = wrapMarkup2 Text.Blaze.Html4.Transitional.optgroup
option :: Markup2
option = wrapMarkup2 Text.Blaze.Html4.Transitional.option
p :: Markup2
p = wrapMarkup2 Text.Blaze.Html4.Transitional.p
pre :: Markup2
pre = wrapMarkup2 Text.Blaze.Html4.Transitional.pre
q :: Markup2
q = wrapMarkup2 Text.Blaze.Html4.Transitional.q
samp :: Markup2
samp = wrapMarkup2 Text.Blaze.Html4.Transitional.samp
script :: Markup2
script = wrapMarkup2 Text.Blaze.Html4.Transitional.script
select :: Markup2
select = wrapMarkup2 Text.Blaze.Html4.Transitional.select
small :: Markup2
small = wrapMarkup2 Text.Blaze.Html4.Transitional.small
span :: Markup2
span = wrapMarkup2 Text.Blaze.Html4.Transitional.span
strong :: Markup2
strong = wrapMarkup2 Text.Blaze.Html4.Transitional.strong
style :: Markup2
style = wrapMarkup2 Text.Blaze.Html4.Transitional.style
sub :: Markup2
sub = wrapMarkup2 Text.Blaze.Html4.Transitional.sub
sup :: Markup2
sup = wrapMarkup2 Text.Blaze.Html4.Transitional.sup
table :: Markup2
table = wrapMarkup2 Text.Blaze.Html4.Transitional.table
tbody :: Markup2
tbody = wrapMarkup2 Text.Blaze.Html4.Transitional.tbody
td :: Markup2
td = wrapMarkup2 Text.Blaze.Html4.Transitional.td
textarea :: Markup2
textarea = wrapMarkup2 Text.Blaze.Html4.Transitional.textarea
tfoot :: Markup2
tfoot = wrapMarkup2 Text.Blaze.Html4.Transitional.tfoot
th :: Markup2
th = wrapMarkup2 Text.Blaze.Html4.Transitional.th
thead :: Markup2
thead = wrapMarkup2 Text.Blaze.Html4.Transitional.thead
title :: Markup2
title = wrapMarkup2 Text.Blaze.Html4.Transitional.title
tr :: Markup2
tr = wrapMarkup2 Text.Blaze.Html4.Transitional.tr
tt :: Markup2
tt = wrapMarkup2 Text.Blaze.Html4.Transitional.tt
ul :: Markup2
ul = wrapMarkup2 Text.Blaze.Html4.Transitional.ul
var :: Markup2
var = wrapMarkup2 Text.Blaze.Html4.Transitional.var
applet :: Markup2
applet = wrapMarkup2 Text.Blaze.Html4.Transitional.applet
center :: Markup2
center = wrapMarkup2 Text.Blaze.Html4.Transitional.center
dir :: Markup2
dir = wrapMarkup2 Text.Blaze.Html4.Transitional.dir
font :: Markup2
font = wrapMarkup2 Text.Blaze.Html4.Transitional.font
iframe :: Markup2
iframe = wrapMarkup2 Text.Blaze.Html4.Transitional.iframe
isindex :: Markup2
isindex = wrapMarkup2 Text.Blaze.Html4.Transitional.isindex
menu :: Markup2
menu = wrapMarkup2 Text.Blaze.Html4.Transitional.menu
noframes :: Markup2
noframes = wrapMarkup2 Text.Blaze.Html4.Transitional.noframes
s :: Markup2
s = wrapMarkup2 Text.Blaze.Html4.Transitional.s
u :: Markup2
u = wrapMarkup2 Text.Blaze.Html4.Transitional.u
docType :: Markup
docType = wrapMarkup Text.Blaze.Html4.Transitional.docType
area :: Markup
area = wrapMarkup Text.Blaze.Html4.Transitional.area
br :: Markup
br = wrapMarkup Text.Blaze.Html4.Transitional.br
col :: Markup
col = wrapMarkup Text.Blaze.Html4.Transitional.col
hr :: Markup
hr = wrapMarkup Text.Blaze.Html4.Transitional.hr
link :: Markup
link = wrapMarkup Text.Blaze.Html4.Transitional.link
img :: Markup
img = wrapMarkup Text.Blaze.Html4.Transitional.img
input :: Markup
input = wrapMarkup Text.Blaze.Html4.Transitional.input
meta :: Markup
meta = wrapMarkup Text.Blaze.Html4.Transitional.meta
param :: Markup
param = wrapMarkup Text.Blaze.Html4.Transitional.param
basefont :: Markup
basefont = wrapMarkup Text.Blaze.Html4.Transitional.basefont

