-- !! DO NOT EDIT
{-|
(Automatically generated by @src\/Util\/GenerateHtmlTCombinators.hs:49@)

This module wraps all exports of "Text.Blaze.XHtml5" using 'wrapMarkup' and 'wrapMarkup'.
-}
module Text.BlazeT.XHtml5
   (module Text.BlazeT.XHtml5
   ,module Text.BlazeT.Html
   ) where
import qualified Text.Blaze.XHtml5
import           Text.BlazeT
import           Text.BlazeT.Html
import           Text.BlazeT.Internal

docTypeHtml :: Markup2
docTypeHtml = wrapMarkup2 Text.Blaze.XHtml5.docTypeHtml
a :: Markup2
a = wrapMarkup2 Text.Blaze.XHtml5.a
abbr :: Markup2
abbr = wrapMarkup2 Text.Blaze.XHtml5.abbr
address :: Markup2
address = wrapMarkup2 Text.Blaze.XHtml5.address
article :: Markup2
article = wrapMarkup2 Text.Blaze.XHtml5.article
aside :: Markup2
aside = wrapMarkup2 Text.Blaze.XHtml5.aside
audio :: Markup2
audio = wrapMarkup2 Text.Blaze.XHtml5.audio
b :: Markup2
b = wrapMarkup2 Text.Blaze.XHtml5.b
bdo :: Markup2
bdo = wrapMarkup2 Text.Blaze.XHtml5.bdo
blockquote :: Markup2
blockquote = wrapMarkup2 Text.Blaze.XHtml5.blockquote
body :: Markup2
body = wrapMarkup2 Text.Blaze.XHtml5.body
button :: Markup2
button = wrapMarkup2 Text.Blaze.XHtml5.button
canvas :: Markup2
canvas = wrapMarkup2 Text.Blaze.XHtml5.canvas
caption :: Markup2
caption = wrapMarkup2 Text.Blaze.XHtml5.caption
cite :: Markup2
cite = wrapMarkup2 Text.Blaze.XHtml5.cite
code :: Markup2
code = wrapMarkup2 Text.Blaze.XHtml5.code
colgroup :: Markup2
colgroup = wrapMarkup2 Text.Blaze.XHtml5.colgroup
command :: Markup2
command = wrapMarkup2 Text.Blaze.XHtml5.command
datalist :: Markup2
datalist = wrapMarkup2 Text.Blaze.XHtml5.datalist
dd :: Markup2
dd = wrapMarkup2 Text.Blaze.XHtml5.dd
del :: Markup2
del = wrapMarkup2 Text.Blaze.XHtml5.del
details :: Markup2
details = wrapMarkup2 Text.Blaze.XHtml5.details
dfn :: Markup2
dfn = wrapMarkup2 Text.Blaze.XHtml5.dfn
div :: Markup2
div = wrapMarkup2 Text.Blaze.XHtml5.div
dl :: Markup2
dl = wrapMarkup2 Text.Blaze.XHtml5.dl
dt :: Markup2
dt = wrapMarkup2 Text.Blaze.XHtml5.dt
em :: Markup2
em = wrapMarkup2 Text.Blaze.XHtml5.em
fieldset :: Markup2
fieldset = wrapMarkup2 Text.Blaze.XHtml5.fieldset
figcaption :: Markup2
figcaption = wrapMarkup2 Text.Blaze.XHtml5.figcaption
figure :: Markup2
figure = wrapMarkup2 Text.Blaze.XHtml5.figure
footer :: Markup2
footer = wrapMarkup2 Text.Blaze.XHtml5.footer
form :: Markup2
form = wrapMarkup2 Text.Blaze.XHtml5.form
h1 :: Markup2
h1 = wrapMarkup2 Text.Blaze.XHtml5.h1
h2 :: Markup2
h2 = wrapMarkup2 Text.Blaze.XHtml5.h2
h3 :: Markup2
h3 = wrapMarkup2 Text.Blaze.XHtml5.h3
h4 :: Markup2
h4 = wrapMarkup2 Text.Blaze.XHtml5.h4
h5 :: Markup2
h5 = wrapMarkup2 Text.Blaze.XHtml5.h5
h6 :: Markup2
h6 = wrapMarkup2 Text.Blaze.XHtml5.h6
head :: Markup2
head = wrapMarkup2 Text.Blaze.XHtml5.head
header :: Markup2
header = wrapMarkup2 Text.Blaze.XHtml5.header
hgroup :: Markup2
hgroup = wrapMarkup2 Text.Blaze.XHtml5.hgroup
html :: Markup2
html = wrapMarkup2 Text.Blaze.XHtml5.html
i :: Markup2
i = wrapMarkup2 Text.Blaze.XHtml5.i
iframe :: Markup2
iframe = wrapMarkup2 Text.Blaze.XHtml5.iframe
ins :: Markup2
ins = wrapMarkup2 Text.Blaze.XHtml5.ins
kbd :: Markup2
kbd = wrapMarkup2 Text.Blaze.XHtml5.kbd
label :: Markup2
label = wrapMarkup2 Text.Blaze.XHtml5.label
legend :: Markup2
legend = wrapMarkup2 Text.Blaze.XHtml5.legend
li :: Markup2
li = wrapMarkup2 Text.Blaze.XHtml5.li
main :: Markup2
main = wrapMarkup2 Text.Blaze.XHtml5.main
map :: Markup2
map = wrapMarkup2 Text.Blaze.XHtml5.map
mark :: Markup2
mark = wrapMarkup2 Text.Blaze.XHtml5.mark
menu :: Markup2
menu = wrapMarkup2 Text.Blaze.XHtml5.menu
meter :: Markup2
meter = wrapMarkup2 Text.Blaze.XHtml5.meter
nav :: Markup2
nav = wrapMarkup2 Text.Blaze.XHtml5.nav
noscript :: Markup2
noscript = wrapMarkup2 Text.Blaze.XHtml5.noscript
object :: Markup2
object = wrapMarkup2 Text.Blaze.XHtml5.object
ol :: Markup2
ol = wrapMarkup2 Text.Blaze.XHtml5.ol
optgroup :: Markup2
optgroup = wrapMarkup2 Text.Blaze.XHtml5.optgroup
option :: Markup2
option = wrapMarkup2 Text.Blaze.XHtml5.option
output :: Markup2
output = wrapMarkup2 Text.Blaze.XHtml5.output
p :: Markup2
p = wrapMarkup2 Text.Blaze.XHtml5.p
pre :: Markup2
pre = wrapMarkup2 Text.Blaze.XHtml5.pre
progress :: Markup2
progress = wrapMarkup2 Text.Blaze.XHtml5.progress
q :: Markup2
q = wrapMarkup2 Text.Blaze.XHtml5.q
rp :: Markup2
rp = wrapMarkup2 Text.Blaze.XHtml5.rp
rt :: Markup2
rt = wrapMarkup2 Text.Blaze.XHtml5.rt
ruby :: Markup2
ruby = wrapMarkup2 Text.Blaze.XHtml5.ruby
samp :: Markup2
samp = wrapMarkup2 Text.Blaze.XHtml5.samp
script :: Markup2
script = wrapMarkup2 Text.Blaze.XHtml5.script
section :: Markup2
section = wrapMarkup2 Text.Blaze.XHtml5.section
select :: Markup2
select = wrapMarkup2 Text.Blaze.XHtml5.select
small :: Markup2
small = wrapMarkup2 Text.Blaze.XHtml5.small
span :: Markup2
span = wrapMarkup2 Text.Blaze.XHtml5.span
strong :: Markup2
strong = wrapMarkup2 Text.Blaze.XHtml5.strong
style :: Markup2
style = wrapMarkup2 Text.Blaze.XHtml5.style
sub :: Markup2
sub = wrapMarkup2 Text.Blaze.XHtml5.sub
summary :: Markup2
summary = wrapMarkup2 Text.Blaze.XHtml5.summary
sup :: Markup2
sup = wrapMarkup2 Text.Blaze.XHtml5.sup
table :: Markup2
table = wrapMarkup2 Text.Blaze.XHtml5.table
tbody :: Markup2
tbody = wrapMarkup2 Text.Blaze.XHtml5.tbody
td :: Markup2
td = wrapMarkup2 Text.Blaze.XHtml5.td
textarea :: Markup2
textarea = wrapMarkup2 Text.Blaze.XHtml5.textarea
tfoot :: Markup2
tfoot = wrapMarkup2 Text.Blaze.XHtml5.tfoot
th :: Markup2
th = wrapMarkup2 Text.Blaze.XHtml5.th
thead :: Markup2
thead = wrapMarkup2 Text.Blaze.XHtml5.thead
time :: Markup2
time = wrapMarkup2 Text.Blaze.XHtml5.time
title :: Markup2
title = wrapMarkup2 Text.Blaze.XHtml5.title
tr :: Markup2
tr = wrapMarkup2 Text.Blaze.XHtml5.tr
ul :: Markup2
ul = wrapMarkup2 Text.Blaze.XHtml5.ul
var :: Markup2
var = wrapMarkup2 Text.Blaze.XHtml5.var
video :: Markup2
video = wrapMarkup2 Text.Blaze.XHtml5.video
docType :: Markup
docType = wrapMarkup Text.Blaze.XHtml5.docType
area :: Markup
area = wrapMarkup Text.Blaze.XHtml5.area
base :: Markup
base = wrapMarkup Text.Blaze.XHtml5.base
br :: Markup
br = wrapMarkup Text.Blaze.XHtml5.br
col :: Markup
col = wrapMarkup Text.Blaze.XHtml5.col
embed :: Markup
embed = wrapMarkup Text.Blaze.XHtml5.embed
hr :: Markup
hr = wrapMarkup Text.Blaze.XHtml5.hr
img :: Markup
img = wrapMarkup Text.Blaze.XHtml5.img
input :: Markup
input = wrapMarkup Text.Blaze.XHtml5.input
keygen :: Markup
keygen = wrapMarkup Text.Blaze.XHtml5.keygen
link :: Markup
link = wrapMarkup Text.Blaze.XHtml5.link
menuitem :: Markup
menuitem = wrapMarkup Text.Blaze.XHtml5.menuitem
meta :: Markup
meta = wrapMarkup Text.Blaze.XHtml5.meta
param :: Markup
param = wrapMarkup Text.Blaze.XHtml5.param
source :: Markup
source = wrapMarkup Text.Blaze.XHtml5.source
track :: Markup
track = wrapMarkup Text.Blaze.XHtml5.track
wbr :: Markup
wbr = wrapMarkup Text.Blaze.XHtml5.wbr

