-- !! DO NOT EDIT
{-|
(Automatically generated by @src\/Util\/GenerateHtmlTCombinators.hs:49@)

This module simply reexports the corresponding @blaze-html@ module.
-}
module Text.BlazeT.Html4.Transitional.Attributes
   (module Text.Blaze.Html4.Transitional.Attributes
   ) where
import Text.Blaze.Html4.Transitional.Attributes

