-- !! DO NOT EDIT
{-|
(Automatically generated by @src\/Util\/GenerateHtmlTCombinators.hs:49@)

This module simply reexports the corresponding @blaze-html@ module.
-}
module Text.BlazeT.XHtml5.Attributes
   (module Text.Blaze.XHtml5.Attributes
   ) where
import Text.Blaze.XHtml5.Attributes

